# Generated by Django 5.2.1 on 2025-06-23 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_rename_address_customer_customer_address_and_more'),
        ('employee', '0001_initial'),
        ('project', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_project', models.CharField(choices=[('DEA', 'DEA'), ('New Design', 'New Design')], max_length=50)),
                ('category_drawing', models.CharField(choices=[('Main', 'Main'), ('Revised-1', 'Revised-1'), ('Revised-2', 'Revised-2'), ('Revised-3', 'Revised-3'), ('Revised-4', 'Revised-4')], max_length=50)),
                ('planned_start', models.DateField()),
                ('planned_finish', models.DateField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progress')),
                ('cause_1', models.CharField(blank=True, choices=[('Client Problem', 'Client Problem'), ('Dzignscape Problem', 'Dzignscape Problem')], max_length=50)),
                ('day_inc_1', models.PositiveIntegerField(default=0)),
                ('cause_2', models.CharField(blank=True, choices=[('Client Problem', 'Client Problem'), ('Dzignscape Problem', 'Dzignscape Problem')], max_length=50)),
                ('day_inc_2', models.PositiveIntegerField(default=0)),
                ('cause_3', models.CharField(blank=True, choices=[('Client Problem', 'Client Problem'), ('Dzignscape Problem', 'Dzignscape Problem')], max_length=50)),
                ('day_inc_3', models.PositiveIntegerField(default=0)),
                ('cause_4', models.CharField(blank=True, choices=[('Client Problem', 'Client Problem'), ('Dzignscape Problem', 'Dzignscape Problem')], max_length=50)),
                ('day_inc_4', models.PositiveIntegerField(default=0)),
                ('cause_5', models.CharField(blank=True, choices=[('Client Problem', 'Client Problem'), ('Dzignscape Problem', 'Dzignscape Problem')], max_length=50)),
                ('day_inc_5', models.PositiveIntegerField(default=0)),
                ('cause_6', models.CharField(blank=True, choices=[('Client Problem', 'Client Problem'), ('Dzignscape Problem', 'Dzignscape Problem')], max_length=50)),
                ('day_inc_6', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('dependency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tasks', to='work_plan.workplan')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Assigned Engineer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
