# Generated by Django 5.2.1 on 2025-06-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplan',
            name='cause_1',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='cause_2',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='cause_3',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='cause_4',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='cause_5',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='cause_6',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='day_inc_1',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='day_inc_2',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='day_inc_3',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='day_inc_4',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='day_inc_5',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='day_inc_6',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='dependency',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='engineer',
        ),
    ]
