# Generated by Django 5.2.1 on 2025-06-22 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_rename_address_customer_customer_address_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(choices=[('GF', 'GF'), ('1F', '1F'), ('2F', '2F'), ('3F', '3F'), ('4F', '4F'), ('5F', '5F'), ('6F', '6F'), ('7F', '7F'), ('RF', 'RF')], max_length=10)),
                ('flat_type', models.CharField(choices=[('Flat-A', 'Flat-A'), ('Flat-B', 'Flat-B'), ('Flat-C', 'Flat-C')], max_length=10)),
                ('unit', models.CharField(choices=[('Sft', 'Sft')], max_length=10)),
                ('quantity', models.FloatField()),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
