# Generated by Django 5.2.1 on 2025-06-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
