# Generated by Django 5.2.1 on 2025-06-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='customer_phone',
        ),
    ]
