# Generated by Django 5.2.1 on 2025-07-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_resource', models.CharField(max_length=100, verbose_name='Name of Resource')),
                ('resource_unit', models.CharField(choices=[('Pcs', 'Pcs'), ('Nos', 'Nos'), ('Kg', 'Kg'), ('Lit', 'Lit')], max_length=10, verbose_name='Resource Unit')),
                ('resource_group', models.CharField(choices=[('Civil', 'Civil work Material'), ('Sanitary', 'Sanitary work Material'), ('Electrical', 'Electrical work Material'), ('NA', 'NA')], max_length=20, verbose_name='Group of Resource')),
            ],
        ),
    ]
