# Generated by Django 5.2.1 on 2025-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_unit',
            field=models.CharField(choices=[('Pcs', 'Pcs'), ('Nos', 'Nos'), ('Kg', 'Kg'), ('Lit', 'Lit'), ('Bag', 'Bag')], max_length=10, verbose_name='Resource Unit'),
        ),
    ]
