# Generated by Django 5.2.1 on 2025-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_employee', models.CharField(max_length=255)),
                ('employee_address', models.CharField(max_length=500)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
