# Generated by Django 5.2.1 on 2025-06-19 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_name', models.CharField(max_length=100)),
                ('work_type', models.CharField(choices=[('SAM', 'SAM')], max_length=10)),
                ('location', models.CharField(choices=[('GF', 'GF'), ('1F', '1F'), ('2F', '2F'), ('3F', '3F'), ('4F', '4F'), ('5F', '5F'), ('6F', '6F'), ('7F', '7F'), ('RF', 'RF')], max_length=10)),
                ('work_unit', models.CharField(choices=[('Sft', 'Sft')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_bill.contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_bill.project')),
            ],
        ),
    ]
